name = "Lean_RV32D"
defaultTargets = ["LeanRV32D"]
moreLeanArgs = ["--tstack=400000"]

[[lean_lib]]
name = "LeanRV32D"
leanOptions.weak.linter.style.nameCheck = false

[[lean_exe]]
name = "run"
root = "LeanRV32D"
